import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "CareerAI Kenya - Build. Analyze. Get Hired.",
  description:
    "AI-powered CV builder for Kenya. Professional CVs, cover letters, and portfolios - generated by AI, analyzed for ATS, paid with M-Pesa.",
  keywords:
    "CV builder, resume builder, Kenya, AI, M-Pesa, cover letter, portfolio",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300&display=swap"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
