"use client";

import Link from "next/link";
import { useState, useEffect } from "react";
import {
  FileText,
  Mail,
  Globe,
  Sparkles,
  BarChart3,
  Upload,
  Smartphone,
  Link as LinkIcon,
  Lock,
  Palette,
  Zap,
  Target,
  FileUp,
  Heart,
  ArrowRight,
  X,
} from "lucide-react";

interface Testimonial {
  id: string;
  name: string;
  role: string;
  company: string;
  content: string;
  avatar: string;
  is_active: boolean;
}

export default function Home() {
  const [showModal, setShowModal] = useState(false);
  const [testimonials, setTestimonials] = useState<Testimonial[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchActiveTestimonials();
  }, []);

  const fetchActiveTestimonials = async () => {
    try {
      const response = await fetch("/api/testimonials/active");
      const data = await response.json();
      if (Array.isArray(data)) {
        setTestimonials(data);
      }
    } catch (error) {
      console.error("Error fetching testimonials:", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      {/* Navigation */}
      <nav>
        <div className="nav-inner">
          <Link href="/" className="nav-logo">
            Career<span>AI</span>
          </Link>
          <div className="nav-center">
            <Link href="/templates#resume" className="nav-link">
              Resume / CV
            </Link>
            <Link href="/templates#coverletter" className="nav-link">
              Cover Letter
            </Link>
            <Link href="/templates#portfolio" className="nav-link">
              Portfolio
            </Link>
            <Link href="/analyzer" className="nav-link">
              ATS Analyzer
            </Link>
          </div>
          <div className="nav-right">
            {typeof window !== "undefined" &&
            localStorage.getItem("isAuthenticated") ? (
              <Link href="/dashboard" className="btn-nav-cta">
                Dashboard
              </Link>
            ) : (
              <Link href="/login" className="btn-nav-cta">
                Log In
              </Link>
            )}
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="hero">
        <div className="hero-dots"></div>
        <div className="hero-glow"></div>

        <div className="hero-badge">
          <span className="badge-dot"></span>
          AI-Powered · Built for Kenya · Pay via M-Pesa
        </div>

        <h1 className="hero-title">
          Build a CV that <span className="green">gets you hired</span>
          <br />
          <span className="dim">in minutes, not days.</span>
        </h1>

        <p className="hero-sub">
          Professional CVs, cover letters and portfolios - generated by AI,
          analyzed for ATS, paid with M-Pesa in 30 seconds.
        </p>

        <div className="hero-ctas">
          <button onClick={() => setShowModal(true)} className="btn-primary">
            Get Started
          </button>
          <a href="#templates" className="btn-outline">
            Browse Templates →
          </a>
        </div>

        <div className="hero-stats">
          <div className="stat">
            <div className="stat-num">
              100<span>Ksh</span>
            </div>
            <div className="stat-label">Full CV forever</div>
          </div>
          <div className="stat-divider"></div>
          <div className="stat">
            <div className="stat-num">
              <span>~</span>3<span>min</span>
            </div>
            <div className="stat-label">Average build time</div>
          </div>
          <div className="stat-divider"></div>
          <div className="stat">
            <div className="stat-num">
              ATS<span>✓</span>
            </div>
            <div className="stat-label">Keyword optimized</div>
          </div>
          <div className="stat-divider"></div>
          <div className="stat">
            <div className="stat-num">
              M<span>-Pesa</span>
            </div>
            <div className="stat-label">Only payment needed</div>
          </div>
        </div>
      </section>

      {/* Get Started Modal */}
      {showModal && (
        <div
          className="modal-overlay"
          onClick={() => setShowModal(false)}
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            background: "rgba(0,0,0,0.6)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            zIndex: 1000,
            backdropFilter: "blur(4px)",
          }}
        >
          <div
            className="modal-content"
            onClick={(e) => e.stopPropagation()}
            style={{
              background: "#fff",
              borderRadius: "20px",
              padding: "40px",
              maxWidth: "480px",
              width: "90%",
              position: "relative",
              boxShadow: "0 25px 50px -12px rgba(0,0,0,0.25)",
            }}
          >
            <button
              onClick={() => setShowModal(false)}
              style={{
                position: "absolute",
                top: "16px",
                right: "16px",
                background: "none",
                border: "none",
                cursor: "pointer",
                color: "var(--muted)",
                padding: "4px",
              }}
            >
              <X size={24} />
            </button>

            <div style={{ textAlign: "center", marginBottom: "32px" }}>
              <h2
                style={{
                  fontSize: "1.5rem",
                  fontWeight: 700,
                  marginBottom: "8px",
                }}
              >
                What would you like to create?
              </h2>
              <p style={{ color: "var(--muted)", fontSize: "0.9rem" }}>
                Choose an option to get started
              </p>
            </div>

            <div
              style={{ display: "flex", flexDirection: "column", gap: "12px" }}
            >
              <Link
                href="/templates#resume"
                onClick={() => setShowModal(false)}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "16px",
                  padding: "20px",
                  border: "1.5px solid var(--border)",
                  borderRadius: "14px",
                  textDecoration: "none",
                  color: "var(--text)",
                  transition: "all 0.2s",
                }}
              >
                <div
                  style={{
                    width: "48px",
                    height: "48px",
                    borderRadius: "12px",
                    background: "var(--green-light)",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    color: "var(--green)",
                  }}
                >
                  <FileText size={24} />
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontWeight: 600, marginBottom: "2px" }}>
                    Create CV / Resume
                  </div>
                  <div style={{ fontSize: "0.8rem", color: "var(--muted)" }}>
                    AI-powered CV builder
                  </div>
                </div>
                <ArrowRight size={20} style={{ color: "var(--muted)" }} />
              </Link>

              <Link
                href="/templates#coverletter"
                onClick={() => setShowModal(false)}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "16px",
                  padding: "20px",
                  border: "1.5px solid var(--border)",
                  borderRadius: "14px",
                  textDecoration: "none",
                  color: "var(--text)",
                  transition: "all 0.2s",
                }}
              >
                <div
                  style={{
                    width: "48px",
                    height: "48px",
                    borderRadius: "12px",
                    background: "var(--green-light)",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    color: "var(--green)",
                  }}
                >
                  <Mail size={24} />
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontWeight: 600, marginBottom: "2px" }}>
                    Cover Letter
                  </div>
                  <div style={{ fontSize: "0.8rem", color: "var(--muted)" }}>
                    AI-generated for any job
                  </div>
                </div>
                <ArrowRight size={20} style={{ color: "var(--muted)" }} />
              </Link>

              <Link
                href="/templates#portfolio"
                onClick={() => setShowModal(false)}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "16px",
                  padding: "20px",
                  border: "1.5px solid var(--border)",
                  borderRadius: "14px",
                  textDecoration: "none",
                  color: "var(--text)",
                  transition: "all 0.2s",
                }}
              >
                <div
                  style={{
                    width: "48px",
                    height: "48px",
                    borderRadius: "12px",
                    background: "var(--green-light)",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    color: "var(--green)",
                  }}
                >
                  <Globe size={24} />
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontWeight: 600, marginBottom: "2px" }}>
                    Portfolio Website
                  </div>
                  <div style={{ fontSize: "0.8rem", color: "var(--muted)" }}>
                    Hosted link to showcase work
                  </div>
                </div>
                <ArrowRight size={20} style={{ color: "var(--muted)" }} />
              </Link>

              <Link
                href="/analyzer"
                onClick={() => setShowModal(false)}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "16px",
                  padding: "20px",
                  border: "1.5px solid var(--border)",
                  borderRadius: "14px",
                  textDecoration: "none",
                  color: "var(--text)",
                  transition: "all 0.2s",
                }}
              >
                <div
                  style={{
                    width: "48px",
                    height: "48px",
                    borderRadius: "12px",
                    background: "var(--green-light)",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    color: "var(--green)",
                  }}
                >
                  <BarChart3 size={24} />
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontWeight: 600, marginBottom: "2px" }}>
                    ATS Analyzer
                  </div>
                  <div style={{ fontSize: "0.8rem", color: "var(--muted)" }}>
                    Score your CV against job descriptions
                  </div>
                </div>
                <ArrowRight size={20} style={{ color: "var(--muted)" }} />
              </Link>
            </div>
          </div>
        </div>
      )}

      {/* Templates Section */}
      <section id="templates" style={{ padding: "80px 0", background: "#fff" }}>
        <div className="container">
          <div style={{ textAlign: "center", marginBottom: "40px" }}>
            <span className="section-label">Templates</span>
            <h2
              className="section-title"
              style={{ maxWidth: "500px", margin: "0 auto 12px" }}
            >
              Professional templates
              <br />
              designed to get noticed
            </h2>
          </div>
          <div className="templates-grid">
            {[
              {
                name: "Modern Green",
                desc: "Tech & IT roles",
                badge: "Popular",
              },
              { name: "Classic Blue", desc: "Corporate & HR", badge: "ATS ✓" },
              { name: "Executive", desc: "Senior leadership", badge: "New" },
              { name: "Minimal", desc: "Every industry", badge: "ATS ✓" },
              { name: "Bold Navy", desc: "Finance & law", badge: "Popular" },
              { name: "Soft Sage", desc: "NGO & education", badge: "New" },
              { name: "Creative Studio", desc: "Design & media", badge: "New" },
              {
                name: "Simple Clean",
                desc: "Clean black & white",
                badge: "ATS ✓",
              },
              { name: "Dev Portfolio", desc: "Developers", badge: "Popular" },
            ].map((template) => (
              <div
                key={template.name}
                style={{
                  background: "#fff",
                  border: "1.5px solid var(--border)",
                  borderRadius: "12px",
                  overflow: "hidden",
                  cursor: "pointer",
                  transition: "all 0.3s",
                }}
              >
                <div
                  style={{
                    height: "140px",
                    background: "#0d1f1a",
                    padding: "12px",
                  }}
                >
                  <div
                    style={{
                      height: "28px",
                      background: "linear-gradient(135deg,#00a844,#00695c)",
                      borderRadius: "5px",
                      marginBottom: "8px",
                    }}
                  ></div>
                  <div
                    style={{
                      height: "3px",
                      width: "50%",
                      background: "#00c853",
                      borderRadius: "2px",
                      marginBottom: "6px",
                    }}
                  ></div>
                  <div
                    style={{
                      height: "3px",
                      background: "rgba(255,255,255,0.1)",
                      borderRadius: "2px",
                      marginBottom: "4px",
                    }}
                  ></div>
                  <div
                    style={{
                      height: "3px",
                      width: "70%",
                      background: "rgba(255,255,255,0.1)",
                      borderRadius: "2px",
                    }}
                  ></div>
                </div>
                <div
                  style={{
                    padding: "12px 14px",
                    borderTop: "1px solid var(--border)",
                  }}
                >
                  <div
                    style={{
                      fontWeight: 700,
                      fontSize: "0.85rem",
                      marginBottom: "2px",
                    }}
                  >
                    {template.name}
                  </div>
                  <div style={{ fontSize: "0.72rem", color: "var(--muted)" }}>
                    {template.desc}
                  </div>
                </div>
              </div>
            ))}
          </div>
          <div style={{ textAlign: "center" }}>
            <Link
              href="/templates"
              className="btn-primary"
              style={{ textDecoration: "none" }}
            >
              View All Templates{" "}
              <ArrowRight size={16} style={{ marginLeft: "6px" }} />
            </Link>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="features-section">
        <div className="container">
          <div style={{ textAlign: "center", marginBottom: "52px" }}>
            <span className="section-label">Features</span>
            <h2
              className="section-title"
              style={{ maxWidth: "500px", margin: "0 auto 12px" }}
            >
              Everything you need
              <br />
              to get hired faster
            </h2>
            <p className="section-sub" style={{ margin: "0 auto" }}>
              Built specifically for Kenyan job seekers - every feature has a
              purpose.
            </p>
          </div>
          <div className="features-grid">
            <div className="feature-card">
              <div className="feature-icon">
                <Sparkles size={24} />
              </div>
              <div className="feature-title">AI Create Mode</div>
              <p className="feature-desc">
                Enter your job title, skills and experience - AI generates a
                complete, professional CV in seconds. No blank page, no
                guessing.
              </p>
              <div className="feature-tag">
                <Zap size={14} /> ~2 minutes average
              </div>
            </div>
            <div className="feature-card">
              <div className="feature-icon">
                <BarChart3 size={24} />
              </div>
              <div className="feature-title">ATS Score Analyzer</div>
              <p className="feature-desc">
                Know exactly why your CV is being rejected. Paste a job
                description and get a full ATS score with keyword gaps and
                AI-fix suggestions.
              </p>
              <div className="feature-tag">
                <Target size={14} /> 0–100 point scoring
              </div>
            </div>
            <div className="feature-card">
              <div className="feature-icon">
                <Upload size={24} />
              </div>
              <div className="feature-title">Upload & Improve</div>
              <p className="feature-desc">
                Already have a CV? Upload your PDF or DOCX - AI restructures it,
                improves language, and optimizes it for ATS automatically.
              </p>
              <div className="feature-tag">
                <FileText size={14} /> PDF & DOCX supported
              </div>
            </div>
            <div className="feature-card">
              <div className="feature-icon">
                <Mail size={24} />
              </div>
              <div className="feature-title">Cover Letter Generator</div>
              <p className="feature-desc">
                Get a tailored cover letter for every job application -
                completely free. AI matches your skills to the job description
                every time.
              </p>
              <div className="feature-tag">Free always</div>
            </div>
            <div className="feature-card">
              <div className="feature-icon">
                <Globe size={24} />
              </div>
              <div className="feature-title">Portfolio Builder</div>
              <p className="feature-desc">
                Showcase your work with a professional portfolio. AI generates
                your bio and project descriptions. Get a hosted link to share
                with employers.
              </p>
              <div className="feature-tag">
                <LinkIcon size={14} /> Shareable hosted link
              </div>
            </div>
            <div className="feature-card">
              <div className="feature-icon">
                <Smartphone size={24} />
              </div>
              <div className="feature-title">M-Pesa Payments</div>
              <p className="feature-desc">
                No credit cards, no bank accounts. Pay once via Safaricom M-Pesa
                STK Push in 30 seconds and own your document forever.
              </p>
              <div className="feature-tag">
                <Lock size={14} /> Powered by Safaricom Daraja
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Testimonials Carousel */}
      <section style={{ padding: "80px 0", background: "var(--green-light)" }}>
        <div className="container">
          <div style={{ textAlign: "center", marginBottom: "48px" }}>
            <span className="section-label">Testimonials</span>
            <h2
              className="section-title"
              style={{ maxWidth: "500px", margin: "0 auto 12px" }}
            >
              Loved by job seekers
              <br />
              across Kenya
            </h2>
          </div>
          {loading ? (
            <div style={{ textAlign: "center", padding: "40px" }}>
              <p style={{ color: "var(--muted)" }}>Loading testimonials...</p>
            </div>
          ) : testimonials.length === 0 ? (
            <div style={{ textAlign: "center", padding: "40px" }}>
              <p style={{ color: "var(--muted)" }}>
                No testimonials yet. Check back soon!
              </p>
            </div>
          ) : (
            <div className="testimonials-track">
              {testimonials.map((testimonial) => (
                <div
                  key={testimonial.id}
                  style={{
                    minWidth: "340px",
                    background: "#fff",
                    border: "1px solid var(--border)",
                    borderRadius: "16px",
                    padding: "28px",
                    boxShadow: "0 4px 16px rgba(0,0,0,0.04)",
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      gap: "4px",
                      marginBottom: "16px",
                    }}
                  >
                    {[...Array(5)].map((_, i) => (
                      <div
                        key={i}
                        style={{
                          width: "16px",
                          height: "16px",
                          background: "#00a844",
                          borderRadius: "50%",
                        }}
                      ></div>
                    ))}
                  </div>
                  <p
                    style={{
                      fontSize: "0.92rem",
                      lineHeight: 1.7,
                      color: "var(--text)",
                      marginBottom: "20px",
                    }}
                  >
                    "{testimonial.content}"
                  </p>
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "12px",
                    }}
                  >
                    <div
                      style={{
                        width: "44px",
                        height: "44px",
                        borderRadius: "50%",
                        background: "var(--green-light)",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        fontWeight: 700,
                        color: "var(--green)",
                      }}
                    >
                      {testimonial.avatar || testimonial.name.charAt(0)}
                    </div>
                    <div>
                      <div style={{ fontWeight: 700, fontSize: "0.9rem" }}>
                        {testimonial.name}
                      </div>
                      <div
                        style={{ fontSize: "0.78rem", color: "var(--muted)" }}
                      >
                        {testimonial.role}
                        {testimonial.company && ` · ${testimonial.company}`}
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </section>

      {/* Footer */}
      <footer>
        <div className="footer-inner">
          <div className="footer-top">
            <div>
              <div className="footer-brand-logo">
                Career<span>AI</span> Kenya
              </div>
              <p className="footer-brand-desc">
                Build. Analyze. Improve. Get Hired.
                <br />
                AI-powered career tools built for East Africa.
                <br />
                Pay via M-Pesa in 30 seconds.
              </p>
              <div
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: "8px",
                  background: "rgba(0,200,83,0.1)",
                  border: "1px solid rgba(0,200,83,0.25)",
                  color: "#66d98a",
                  fontSize: "0.72rem",
                  fontWeight: "600",
                  padding: "7px 14px",
                  borderRadius: "8px",
                }}
              >
                <Smartphone size={14} /> Payments via Safaricom M-Pesa
              </div>
            </div>
            <div className="footer-col">
              <div className="footer-col-title">Products</div>
              <ul>
                <li>
                  <a href="/builder">
                    <FileText size={14} /> Resume / CV Builder
                  </a>
                </li>
                <li>
                  <a href="/templates">
                    <Mail size={14} /> Cover Letter
                  </a>
                </li>
                <li>
                  <a href="/templates">
                    <Globe size={14} /> Portfolio Builder
                  </a>
                </li>
                <li>
                  <a href="/builder">
                    <BarChart3 size={14} /> ATS Analyzer
                  </a>
                </li>
                <li>
                  <a href="/templates">
                    <Palette size={14} /> Templates
                  </a>
                </li>
              </ul>
            </div>
            <div className="footer-col">
              <div className="footer-col-title">Resources</div>
              <ul>
                <li>
                  <a href="#">CV Writing Tips</a>
                </li>
                <li>
                  <a href="#">ATS Guide</a>
                </li>
                <li>
                  <a href="#">Cover Letter Examples</a>
                </li>
                <li>
                  <a href="#">Blog</a>
                </li>
                <li>
                  <a href="#">Career Advice</a>
                </li>
              </ul>
            </div>
            <div className="footer-col">
              <div className="footer-col-title">Company</div>
              <ul>
                <li>
                  <a href="#">About Us</a>
                </li>
                <li>
                  <a href="#">Contact</a>
                </li>
                <li>
                  <a href="#">Privacy Policy</a>
                </li>
                <li>
                  <a href="#">Terms of Service</a>
                </li>
                <li>
                  <a href="#">Refund Policy</a>
                </li>
              </ul>
            </div>
          </div>
          <div className="footer-bottom">
            <p>
              © 2025 CareerAI Kenya. All rights reserved. Made with{" "}
              <Heart size={14} style={{ display: "inline", margin: "0 2px" }} />{" "}
              in Kenya.
            </p>
          </div>
        </div>
      </footer>
    </>
  );
}
